In [1]:
import torch

## indexing

In [2]:
tensor1=torch.tensor([[10,20,30],[40,50,60],[70,80,90]])
print(tensor1.ndim)
print(tensor1.shape)

2
torch.Size([3, 3])


In [3]:
print("element at (0,1): ",tensor1[0,1])

element at (0,1):  tensor(20)


In [7]:
#first row
tensor1[0]

tensor([10, 20, 30])

In [8]:
# first column
tensor1[:,0]

tensor([10, 40, 70])

## Slicing

In [9]:
print("First two rows: ",tensor1[:2])

First two rows:  tensor([[10, 20, 30],
        [40, 50, 60]])


In [10]:
print("first 2 columns: ",tensor1[:,:2])

first 2 columns:  tensor([[10, 20],
        [40, 50],
        [70, 80]])


In [15]:
# middle elements (row 1 and cols 1 and 2)
print(tensor1[1,1:3])

tensor([50, 60])


In [16]:
# fancy indexing
#(0,1)-->20
#(2,2)-->90
print(tensor1[[0,2],[1,2]])

tensor([20, 90])


In [19]:
#boolean indexing
mask =tensor1>=50
print(mask)
print(tensor1[mask])

tensor([[False, False, False],
        [False,  True,  True],
        [ True,  True,  True]])
tensor([50, 60, 70, 80, 90])


In [20]:
# changing vals via indexing
print(tensor1)
tensor1[0,1]=25
print(tensor1)

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
tensor([[10, 25, 30],
        [40, 50, 60],
        [70, 80, 90]])


In [21]:
tensor1[:,0]=torch.tensor([100,200,300])
print(tensor1)

tensor([[100,  25,  30],
        [200,  50,  60],
        [300,  80,  90]])


In [24]:
indices=torch.tensor([0,2])
selected_rows=torch.index_select(tensor1,dim=0,index=indices)
print(selected_rows)

tensor([[100,  25,  30],
        [300,  80,  90]])


In [26]:
# using tensor with steps
print(tensor1[:,::2])

tensor([[100,  30],
        [200,  60],
        [300,  90]])


In [32]:
print(torch.flip(tensor1,dims=(0,)))

tensor([[300,  80,  90],
        [200,  50,  60],
        [100,  25,  30]])
