In [1]:
import torch

In [2]:
tensor1=torch.tensor([1,2,3])
tensor2=torch.tensor([4,5,6])
print(tensor1.ndim)
print(tensor1.size())

1
torch.Size([3])


In [3]:
stacked_tensor_dim0=torch.stack((tensor1,tensor2),dim=0)
print('shape: ',stacked_tensor_dim0.shape)
print(stacked_tensor_dim0)
stacked_tensor_dim1=torch.stack((tensor1,tensor2),dim=1)
print('shape: ',stacked_tensor_dim1.shape)
print(stacked_tensor_dim1)



shape:  torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
shape:  torch.Size([3, 2])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [4]:
tensor3=torch.tensor([7,8,9])
stacked_tensor_dim0=torch.stack((tensor1,tensor2,tensor3),dim=0)
print('shape: ',stacked_tensor_dim0.shape)
print(stacked_tensor_dim0)

shape:  torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [5]:
tensor1=torch.tensor([[1,2],[3,4]])
tensor2=torch.tensor([[5,6],[7,8]])
stacked2d=torch.stack((tensor1,tensor2),dim=0)
print('shape',stacked2d.shape)
print(stacked2d)


shape torch.Size([2, 2, 2])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [6]:
stacked2d_dim1=torch.stack((tensor1,tensor2),dim=1)
print('shape',stacked2d_dim1.shape)
print(stacked2d_dim1)

shape torch.Size([2, 2, 2])
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


In [7]:
stacked2d_dim2=torch.stack((tensor1,tensor2),dim=2)
print('shape',stacked2d_dim2.shape)
print(stacked2d_dim2)

shape torch.Size([2, 2, 2])
tensor([[[1, 5],
         [2, 6]],

        [[3, 7],
         [4, 8]]])


In [8]:
concat=torch.cat((tensor1,tensor2),dim=0)
print('shape',concat.shape)
print(concat)

shape torch.Size([4, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [9]:
concat=torch.cat((tensor1,tensor2),dim=1)
print('shape',concat.shape)
print(concat)

shape torch.Size([2, 4])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
