## tensor manipulation
- reshaping
- slicing
- joining or splitting
- transposing and permuting dimension

In [1]:
import torch

In [3]:
#reshaping tensors
#reshape
#view

og_tensor=torch.arange(12)
print(og_tensor)
print(og_tensor.nelement())
print(og_tensor.ndim)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
12
1


In [4]:
reshaped_tensor=og_tensor.reshape(2,6)
print(reshaped_tensor)
print(reshaped_tensor.ndim)
print(reshaped_tensor.nelement())

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
2
12


In [5]:
reshaped_tensor=og_tensor.reshape(3,4)
print(reshaped_tensor)
print(reshaped_tensor.ndim)
print(reshaped_tensor.nelement())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
2
12


In [8]:
#view
print(reshaped_tensor.is_contiguous())
flattened_tensor=reshaped_tensor.view(-1)
print(flattened_tensor)

True
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


## Slicing 
Extract specific portions of tensors

In [9]:
tensor_a=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(tensor_a)
print(tensor_a.ndim)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2


In [10]:
print(tensor_a[0])

tensor([1, 2, 3])


In [11]:
tensor_a[:,2]

tensor([3, 6, 9])

In [12]:
tensor_a.shape

torch.Size([3, 3])

In [13]:
sub=tensor_a[1:,1:]
print(sub.shape)
print(sub)

torch.Size([2, 2])
tensor([[5, 6],
        [8, 9]])


## joining tensors

In [16]:
#torch.cat()--> merges tensors along an existing dimension
tensor1=torch.tensor([[1,2],[3,4]])
tensor2=torch.tensor([[5,6],[7,8]])

concat_tensor_rows=torch.cat((tensor1,tensor2),dim=0)
concat_tensor_cols=torch.cat((tensor1,tensor2),dim=1)
print(concat_tensor_rows)
print(concat_tensor_cols)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [19]:
#stack --> created a new dimension, increases the tensors rank
stack_tensor_rows=torch.stack((tensor1,tensor2),dim=0)
stack_tensor_cols=torch.stack((tensor1,tensor2),dim=1)
print(stack_tensor_rows)
print(stack_tensor_rows.shape)
print("="*20)
print(stack_tensor_cols)
print(stack_tensor_cols.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])
torch.Size([2, 2, 2])


## splitting tensors
- torch.chunk()--> divides your tensor into equal-sized chunks
- torch.split()-> allows uneven splitting based on size

In [22]:
#torch.chunk
og_tensor=torch.arange(12)
chunks=torch.chunk(og_tensor,5,dim=0)
print(chunks)

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([ 9, 10, 11]))


In [21]:
for chunk in chunks:
    print(chunk)

tensor([0, 1, 2, 3])
tensor([4, 5, 6, 7])
tensor([ 8,  9, 10, 11])


In [23]:
#torch.split
splits=torch.split(og_tensor,5,dim=0)
print(splits)
for split in splits:
    print(split)

(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9]), tensor([10, 11]))
tensor([0, 1, 2, 3, 4])
tensor([5, 6, 7, 8, 9])
tensor([10, 11])


## Transposing and permuting
- transpose()--> swaps two dimensions -->nxm
- permute()--> rearranges all dimensions in the specified order

In [25]:
tensor_og=torch.arange(24).reshape(12,2)
transposed=tensor_og.transpose(0,1)
print(tensor_og)
print(tensor_og.shape)
print(transposed.shape)
print(transposed)


tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])
torch.Size([12, 2])
torch.Size([2, 12])
tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])


In [27]:
tensor_og=torch.arange(24).reshape(2,3,4)
permuted=tensor_og.permute(2,0,1)
print(tensor_og)
print("="*30)
print(permuted)


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[ 0,  4,  8],
         [12, 16, 20]],

        [[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]]])


## cloning and detaching

In [28]:
import copy
a=[1,2,3]
b=copy.deepcopy(a)
print(a)
print(b)

[1, 2, 3]
[1, 2, 3]


In [29]:
tensor=torch.ones(3,3,requires_grad=True)#part of computation graph
cloned=tensor.clone()#part of computation graph
detached=tensor.detach()# this code will detach the tensor from the comutaion graph
#not a part of computation graph
#but storage will be the same as the original one
