In [1]:
import torch

In [2]:
tensor=torch.arange(12)

In [4]:
reshaped_tensor_view=tensor.view(2,6)
reshaped_tensor_reshape=tensor.reshape(2,6)
print(reshaped_tensor_view)
print(reshaped_tensor_reshape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [5]:
print(tensor.is_contiguous())
print(reshaped_tensor_view.is_contiguous())
print(reshaped_tensor_reshape.is_contiguous())

True
True
True


In [6]:
inferred_shape=tensor.view(3,-1)
print(inferred_shape)
print(inferred_shape.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [7]:
tensor_3d=torch.arange(24).reshape(2,3,4)
print(tensor_3d)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [8]:
flattened=tensor_3d.view(-1)
print(flattened)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])


In [9]:
flattened.is_contiguous()

True

In [10]:
tensor2d=torch.arange(24).reshape(12,2)
transpose_tensor=tensor2d.t()

In [11]:
transpose_tensor.is_contiguous()

False

In [13]:
error=transpose_tensor.reshape(6,4)

In [14]:
print(error)

tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [17, 19, 21, 23]])


In [15]:
contigious=transpose_tensor.contiguous()
error=contigious.view(6,4)